---
ID: "bbe4bfbb-953c-4988-8608-5459e60949d2"
Parent: "10e23679-55db-4059-b8f2-e417a2f78fcb"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Analytics/Federated Experience Manager/Filters and Actions/Element Placeholder/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140318T123857
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
