---
ID: "32e86b66-1837-423d-a34a-fe82c6371170"
Parent: "98ba1330-4412-4fcb-8cd5-9818a781d3cc"
Template: "98ba1330-4412-4fcb-8cd5-9818a781d3cc"
Path: /sitecore/templates/Feature/Experience Accelerator/Composites/Rendering Parameters/Tabs/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111207T111100
