---
ID: "afc92c98-3bc9-48e9-816e-828eaf7dc750"
Parent: "f05212ce-30a7-4733-a7f4-ed6e13f26692"
Template: "f05212ce-30a7-4733-a7f4-ed6e13f26692"
Path: /sitecore/templates/System/Webhooks/Webhook Event Handler/__Standard Values
DB: master
SharedFields:
- ID: "70bcf39c-e567-4bc5-9dfa-3503810ef820"
  Hint: Enabled
  Type: Checkbox
  Value: 0
- ID: "9a9f209c-eac3-4fd0-ade1-7760c4e7b8ff"
  Hint: Serialization Type
  Value: "{9844BCA0-5FA6-48C8-B4A3-171A2BE6E5C2}"
- ID: "f9f59338-045d-4da8-80f0-ce7f7d92e4af"
  Hint: Url
  Value: "https://"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210908T094652Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
