---
ID: "b54f22aa-57d2-40f5-bbd0-14210c2f6a80"
Parent: "e43cb7ec-44a5-4a92-9eb6-f1ca7a385c5d"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Content Testing/Workflow/Remove Tests Action/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141107T013307Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
