---
ID: "e687c094-81af-5561-ae77-3211b0768b32"
Parent: "c0c6531e-dc6f-5743-9704-7f17dfc75c72"
Template: "c0c6531e-dc6f-5743-9704-7f17dfc75c72"
Path: "/sitecore/templates/Project/my-alexa-jss-app/GraphQL-ConnectedDemo Rendering Parameters/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230306T084805Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
