---
ID: "2f3e7db2-0ff1-5909-9ba0-a3c727cbfe70"
Parent: "adac107f-f150-528e-9f75-1396b89303e0"
Template: "adac107f-f150-528e-9f75-1396b89303e0"
Path: "/sitecore/templates/Project/my-alexa-jss-app/GraphQL-IntegratedDemo Rendering Parameters/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230306T084805Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
