---
ID: "b31a99ff-fd7c-483e-b1c9-5e13d141b01c"
Parent: "c9efab00-e3a8-41f2-94dd-9983aafa641e"
Template: "c9efab00-e3a8-41f2-94dd-9983aafa641e"
Path: /sitecore/templates/System/Email/Common Template/Parameter Templates/Basic/Button/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
- ID: "7cd4972a-a72b-4635-a1d9-c8c097e0d355"
  Hint: Button Color
  Value: #232323
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160816T060246Z
