---
ID: "dbdceaf3-cab9-43e3-bc44-0ace326a8c7c"
Parent: "b36ba9fd-0dc0-49c8-bea2-e55d70e6af28"
Template: "b36ba9fd-0dc0-49c8-bea2-e55d70e6af28"
Path: /sitecore/templates/Foundation/JavaScript Services/Route/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161114T192701Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
