---
ID: "d0cda191-49a9-4e30-acac-40f7f2643c97"
Parent: "06f366e6-a7e6-470b-9ec9-cd29a4f6c8e8"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Templates/Sections/Workflow/Workflow
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: network/16x16/outbox.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 999999
- ID: "e2e2b75d-a2f7-4075-bde2-d13306e9e350"
  Hint: Collapsed by Default
  Type: checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
