---
ID: "5843deb0-8893-4c7d-9365-07d900fa30c5"
Parent: "88c2d31d-26c3-492b-9846-7c02681bdb91"
Template: "88c2d31d-26c3-492b-9846-7c02681bdb91"
Path: /sitecore/templates/System/Services/Throttle/Strategy/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171206T144951Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
