---
ID: "ee1023c8-430b-4b52-a1ef-9f3fd4c5699f"
Parent: "448108a3-cea9-42e3-a86c-2d2bd325870e"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Experience Accelerator/SiteMetadata/Base/_SitemapMediaItems/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220209T061922Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
