---
ID: "ce4aee88-fd5d-4a1c-ae3c-3dd578dd32f9"
Parent: "196c81c4-b742-4e20-a050-bdb40c531f91"
Template: "196c81c4-b742-4e20-a050-bdb40c531f91"
Path: /sitecore/templates/System/Email/Common Template/Section Content/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160816T055446Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7fe15d37-ccaa-4ff2-83ba-11b975ba355a"
      Hint: Heading
      Value: $name
