---
ID: "715ba68d-500d-4c0c-a611-8ad2b3478b21"
Parent: "22e4ce0c-bbbc-46ec-8f36-773779104491"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/templates/Branches/Feature/JSS Experience Accelerator/Media/Default Headless Image Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211021T091535Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
