---
ID: "38069d83-16e5-4533-998a-e9e9e13b508d"
Parent: "89ae4677-9391-4267-ab7a-ee3b063a1be0"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: /sitecore/templates/Branches/System/Rules/Taxonomy/Rules Context Folder/$name/Tags/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120801T210913
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
