---
ID: "43f1e052-8338-45cd-aee7-ca6c1b6d50f3"
Parent: "ab811af4-393c-4a46-acd7-81d30917e7f4"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Templates/Sections/Security/Security
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Network/24x24/lock.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 999999
- ID: "e2e2b75d-a2f7-4075-bde2-d13306e9e350"
  Hint: Collapsed by Default
  Type: checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
