---
ID: "7a863c30-91f5-5f66-a340-52e601316a05"
Parent: "d32f0652-3fe2-5536-8045-9f3549a6ac56"
Template: "d32f0652-3fe2-5536-8045-9f3549a6ac56"
Path: "/sitecore/templates/Project/my-alexa-jss-app/Styleguide-Section Rendering Parameters/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230306T084808Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
