---
ID: "611c1f20-e2c1-49d1-b02d-4354aacb1842"
Parent: "2013052c-0c2f-4645-b886-108c749b565f"
Template: "2013052c-0c2f-4645-b886-108c749b565f"
Path: /sitecore/templates/System/Webhooks/Authorization/OAuth2PasswordCredentialsGrant/__Standard Values
DB: master
SharedFields:
- ID: "82e95a61-d131-493c-a5bc-d22951abdff9"
  Hint: Authority URL
  Value: "https://"
- ID: "b4d04eee-083b-435b-a96f-d83be00d7cca"
  Hint: Header Prefix
  Value: Bearer
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211104T105111Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
