---
ID: "bc041095-6b44-4280-85ba-1e978cef2ed0"
Parent: "a82e8931-0575-4175-917d-e904ef7e6dbe"
Template: "a82e8931-0575-4175-917d-e904ef7e6dbe"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Title/__Standard Values
DB: master
SharedFields:
- ID: "0793dcff-0ee7-48ad-b9d4-ef1dd24eb59b"
  Hint: Data Source
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211020T140508Z
