---
ID: "ac47bea7-3514-4ae9-ba37-088d54b6dbe1"
Parent: "036db470-1850-4848-a48a-0931f825b867"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Analytics/Federated Experience Manager/Domain Matcher/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140227T141448
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
